version: "3"

networks:
  proxy:

secrets:
  TUNNEL_TOKEN:
    file: ${BASE_DIR}/secrets/tunnel_token.txt

services:

  proxymanager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./config/nginx-proxy-manager/proxy-manager:/data
      - ./config/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}

  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/config/organizr:/config
    ports:
      - "9000:80"
    restart: unless-stopped

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=/run/secrets/TUNNEL_TOKEN
    secrets:
      - TUNNEL_TOKEN

  # traefik-reverse-proxy:
  #   # The official v2 Traefik docker image
  #   image: traefik:v2.10
  #   # Enables the web UI and tells Traefik to listen to docker
  #   command: --api.insecure=true --providers.docker
  #   ports:
  #     # The HTTP port
  #     - "80:80"
  #     # The Web UI (enabled by --api.insecure=true)
  #     - "9090:8080"
  #   volumes:
  #     # So that Traefik can listen to the Docker events
  #     - /var/run/docker.sock:/var/run/docker.sock