---
version: "3"

volumes:
  movies:
    driver_opts:
      type: "nfs4"
      o: "nfsvers=4,addr=192.168.1.10,nolock,soft,rw"
      device: ":/mnt/v1_rz2/movies"
  series:
    driver_opts:
      type: "nfs4"
      o: "nfsvers=4,addr=192.168.1.10,nolock,soft,rw"
      device: ":/mnt/v1_rz2/series"
#   downloads:
#     driver_opts:
#       type: "nfs4"
#       o: "nfsvers=4,addr=192.168.1.10,nolock,soft,rw"
#       device: ":/mnt/v1_rz2/downloads"
#   apps:
#     driver_opts:
#       type: "nfs4"
#       o: "nfsvers=4,addr=192.168.1.10,nolock,soft,rw"
#       device: ":/mnt/v1_rz2/apps"

services:
  # https://hub.docker.com/r/linuxserver/jackett
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./jackett:/config
      - /mnt/downloads/watch:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped
    labels:
      group: "media"

  # https://hub.docker.com/r/linuxserver/qbittorrent
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - UMASK_SET=002
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - /mnt/downloads:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    restart: unless-stopped
    labels:
      group: "media"

  # https://hub.docker.com/r/linuxserver/radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - UMASK_SET=002
    volumes:
      - ./radarr/config:/config
      - /mnt:/media
    ports:
      - "7878:7878"
    restart: unless-stopped
    labels:
      group: "media"

  # https://hub.docker.com/r/linuxserver/sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - UMASK_SET=002 #optional
    volumes:
      - ./sonarr/config:/config
      - /mnt:/media
    ports:
      - "8989:8989"
    restart: unless-stopped
    labels:
      group: "media"

  # # https://hub.docker.com/r/linuxserver/bazarr
  # bazarr:
  #   image: linuxserver/bazarr:latest
  #   container_name: bazarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Australia/Sydney
  #     - UMASK_SET=002
  #   volumes:
  #     - ./bazarr/config:/config
  #     - /mnt/movies:/movies
  #     - /mnt/series:/tv
  #   ports:
  #     - "6767:6767"
  #   restart: unless-stopped
  #   labels:
  #     group: "media"

  # # https://hub.docker.com/r/linuxserver/ombi
  # ombi:
  #   image: linuxserver/ombi
  #   container_name: ombi
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Australia/Sydney
  #   volumes:
  #     - ./ombi/config:/config
  #   ports:
  #     - "3579:3579"
  #   restart: unless-stopped
  #   labels:
  #     group: "media"

  # # https://hub.docker.com/r/linuxserver/organizr
  # organizr:
  #   container_name: organizr
  #   hostname: organizr
  #   image: organizr/organizr
  #   restart: unless-stopped
  #   volumes:
  #     - ./organizr/config:/config
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   environment:
  #     - fpm=true
  #     - branch=v2-master
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Australia/Sydney
  #   labels:
  #     group: "media"
