version: "3"

networks:
  jellyfin:

services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/config/jellyfin:/config
      - ${BASE_DIR}/data/media:/data
    ports:
      - "8096:8096"
    restart: unless-stopped
    networks:
      - jellyfin
