version: "3"

secrets:
  PLEX_CLAIM:
    file: ${BASE_DIR}/secrets/plex_claim.txt

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - VERSION=docker
      - PLEX_CLAIM=/run/secrets/PLEX_CLAIM
      - ADVERTISE_IP="http://${IP}:32400/"
    volumes:
      - ${BASE_DIR}/config/plex:/config
      - ${BASE_DIR}/data/media:/media
    secrets:
      - PLEX_CLAIM
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/config/tautulli:/config
    ports:
      - "8181:8181"
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    depends_on:
      - plex
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/config/overseerr:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped