version: "3.1"

secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assume that secrets are kept in local folder called ".secrets"
  PLEX_CLAIM:
    file: ./plex_claim.txt

services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/config/jellyfin:/config
      - ${BASE_DIR}/data/media:/data
    ports:
      - "8096:8096"
    restart: unless-stopped
