---
version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /mnt/truenas/config/sonarr-config:/config
      - /mnt/truenas/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /mnt/truenas/config/radarr-config:/config
      - /mnt/truenas/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=13009
      - PGID=13000
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /mnt/truenas/config/overseerr-config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /mnt/truenas/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=claim-q3omNzt2fjzyKR84bQRv
    volumes:
      - /mnt/truenas/config/plex-config:/config
      - /mnt/truenas/data/media:/media
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=${UID}
      - PGID=13000
      - TZ=Australia/Sydney
    volumes:
      - /mnt/truenas/config/tautulli-config:/config
    ports:
      - "8181:8181"
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /mnt/truenas/config/jellyfin-config:/config
      - /mnt/truenas/data/media:/data
    ports:
      - "8096:8096"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=Australia/Sydney
      - WEBUI_PORT=8080
    volumes:
      - /mnt/truenas/config/qbittorrent-config:/config
      - /mnt/truenas/data/torrents:/data/torrents
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

