version: "3"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/config/sonarr:/config
      - ${BASE_DIR}/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/config/radarr:/config
      - ${BASE_DIR}/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${BASE_DIR}/config/qbittorrent:/config
      - ${BASE_DIR}/data/torrents:/data/torrents
    ports:
      - "8080:8080"
      # - "6881:6881" # default container ports
      # - "6881:6881/udp"
      - "60881:60881"  # custom container ports
      - "60881:60881/udp"
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}:/srv
      - ${BASE_DIR}/config/filebrowser/config:/config
      - ${BASE_DIR}/config/filebrowser/database:/database
    ports:
      - "9999:80"
    restart: unless-stopped
